name: Diffblue Cover
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  diffblue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for Diffblue to calculate code changes
          persist-credentials: true

      - name: Diffblue Cover Pipeline
        uses: diffblue/cover-github-action@v2024.04.01
        with:
          license-key: ${{ secrets.DIFFBLUE_LICENSE_KEY }}
          access-token: ${{ secrets.DIFFBLUE_ACCESS_TOKEN }}
